import { getUsername } from './utils';

export const Constants = {
	ME: getUsername(),
	MEMORY_RESYNC_INTERVAL: 500,
	MAX_REPAIR_LIMIT: {
		1: 1000,
		2: 1000,
		3: 2000,
		4: 4000,
		5: 8000,
		6: 15000,
		7: 20000,
		8: 40000,
	},
	CONSTRUCTION_PRIORITY: [
		STRUCTURE_SPAWN,
		STRUCTURE_EXTENSION,
		STRUCTURE_LINK,
		STRUCTURE_TOWER,
		STRUCTURE_STORAGE,
		STRUCTURE_CONTAINER,
		STRUCTURE_EXTRACTOR,
		STRUCTURE_ROAD,
		STRUCTURE_TERMINAL,
		STRUCTURE_LAB,
		STRUCTURE_OBSERVER,
		STRUCTURE_POWER_SPAWN,
		STRUCTURE_NUKER,
		STRUCTURE_RAMPART,
		STRUCTURE_WALL,
	],
};
